[2025-07-22T10:32:16.792+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [queued]>
[2025-07-22T10:32:16.837+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [queued]>
[2025-07-22T10:32:16.887+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-22T10:32:16.957+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 04:00:00+00:00
[2025-07-22T10:32:16.986+0000] {standard_task_runner.py:60} INFO - Started process 206 to run task
[2025-07-22T10:32:16.993+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T04:00:00+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp2obqfbfj']
[2025-07-22T10:32:16.998+0000] {standard_task_runner.py:88} INFO - Job 263: Subtask Load_songplays_fact_table
[2025-07-22T10:32:17.123+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [running]> on host a2a13a541787
[2025-07-22T10:32:17.304+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T04:00:00+00:00'
[2025-07-22T10:32:17.310+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 168, in <lambda>
    python_callable=lambda: load_table(SqlQueries.songplay_table_insert),
  File "/opt/airflow/dags/etl_pipeline.py", line 127, in load_table
    cur.execute(f"DELETE FROM {query.split()[3]}")
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 1: DELETE FROM events.start_time)
                                     ^

[2025-07-22T10:32:17.320+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T040000, start_date=20250722T103216, end_date=20250722T103217
[2025-07-22T10:32:17.376+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 263 for task Load_songplays_fact_table (syntax error at or near ")"
LINE 1: DELETE FROM events.start_time)
                                     ^
; 206)
[2025-07-22T10:32:17.401+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-22T10:32:17.446+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T15:59:24.881+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [queued]>
[2025-07-24T15:59:24.888+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [queued]>
[2025-07-24T15:59:24.889+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T15:59:24.902+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 04:00:00+00:00
[2025-07-24T15:59:24.911+0000] {standard_task_runner.py:60} INFO - Started process 1394 to run task
[2025-07-24T15:59:24.915+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T04:00:00+00:00', '--job-id', '1247', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmparw8onzy']
[2025-07-24T15:59:24.917+0000] {standard_task_runner.py:88} INFO - Job 1247: Subtask Load_songplays_fact_table
[2025-07-24T15:59:24.975+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [running]> on host c53547d84df1
[2025-07-24T15:59:25.050+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T04:00:00+00:00'
[2025-07-24T15:59:25.356+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 173, in <lambda>
    python_callable=lambda: load_table(SqlQueries.songplay_table_insert, 'songplays'),
  File "/opt/airflow/dags/etl_pipeline.py", line 132, in load_table
    cur.execute(f"INSERT INTO {table} {query}")
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "songplays_pkey"
DETAIL:  Key (playid)=(e30eb65b5ce5534fed9764a7996916ec) already exists.

[2025-07-24T15:59:25.368+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T040000, start_date=20250724T155924, end_date=20250724T155925
[2025-07-24T15:59:25.378+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1247 for task Load_songplays_fact_table (duplicate key value violates unique constraint "songplays_pkey"
DETAIL:  Key (playid)=(e30eb65b5ce5534fed9764a7996916ec) already exists.
; 1394)
[2025-07-24T15:59:25.408+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T15:59:25.440+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T16:34:37.955+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [queued]>
[2025-07-24T16:34:37.991+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [queued]>
[2025-07-24T16:34:37.992+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T16:34:38.052+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 04:00:00+00:00
[2025-07-24T16:34:38.101+0000] {standard_task_runner.py:60} INFO - Started process 1250 to run task
[2025-07-24T16:34:38.115+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T04:00:00+00:00', '--job-id', '1627', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpkt17cu07']
[2025-07-24T16:34:38.131+0000] {standard_task_runner.py:88} INFO - Job 1627: Subtask Load_songplays_fact_table
[2025-07-24T16:34:38.334+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [running]> on host c53547d84df1
[2025-07-24T16:34:38.561+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T04:00:00+00:00'
[2025-07-24T16:34:38.758+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-24T16:34:38.815+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T040000, start_date=20250724T163437, end_date=20250724T163438
[2025-07-24T16:34:38.918+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-24T16:34:39.001+0000] {taskinstance.py:3280} INFO - 4 downstream tasks scheduled from follow-on schedule check
[2025-07-24T17:13:31.091+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [queued]>
[2025-07-24T17:13:31.107+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [queued]>
[2025-07-24T17:13:31.108+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T17:13:31.126+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 04:00:00+00:00
[2025-07-24T17:13:31.137+0000] {standard_task_runner.py:60} INFO - Started process 1216 to run task
[2025-07-24T17:13:31.145+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T04:00:00+00:00', '--job-id', '2017', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp9is11rsu']
[2025-07-24T17:13:31.158+0000] {standard_task_runner.py:88} INFO - Job 2017: Subtask Load_songplays_fact_table
[2025-07-24T17:13:31.354+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T04:00:00+00:00 [running]> on host 5def55d2a1b5
[2025-07-24T17:13:31.490+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T04:00:00+00:00'
[2025-07-24T17:13:34.249+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-24T17:13:34.262+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T040000, start_date=20250724T171331, end_date=20250724T171334
[2025-07-24T17:13:34.331+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-24T17:13:34.379+0000] {taskinstance.py:3280} INFO - 4 downstream tasks scheduled from follow-on schedule check
