[2025-07-22T10:32:17.041+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2025-07-22T10:32:17.054+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2025-07-22T10:32:17.055+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-22T10:32:17.181+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 00:00:00+00:00
[2025-07-22T10:32:17.189+0000] {standard_task_runner.py:60} INFO - Started process 207 to run task
[2025-07-22T10:32:17.192+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpykd6alb3']
[2025-07-22T10:32:17.195+0000] {standard_task_runner.py:88} INFO - Job 264: Subtask Load_songplays_fact_table
[2025-07-22T10:32:17.404+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [running]> on host a2a13a541787
[2025-07-22T10:32:17.546+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:00:00+00:00'
[2025-07-22T10:32:17.559+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 168, in <lambda>
    python_callable=lambda: load_table(SqlQueries.songplay_table_insert),
  File "/opt/airflow/dags/etl_pipeline.py", line 127, in load_table
    cur.execute(f"DELETE FROM {query.split()[3]}")
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 1: DELETE FROM events.start_time)
                                     ^

[2025-07-22T10:32:17.594+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T000000, start_date=20250722T103217, end_date=20250722T103217
[2025-07-22T10:32:17.612+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 264 for task Load_songplays_fact_table (syntax error at or near ")"
LINE 1: DELETE FROM events.start_time)
                                     ^
; 207)
[2025-07-22T10:32:17.646+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-22T10:32:17.690+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T15:54:44.798+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2025-07-24T15:54:44.817+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2025-07-24T15:54:44.818+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T15:54:44.844+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 00:00:00+00:00
[2025-07-24T15:54:44.863+0000] {standard_task_runner.py:60} INFO - Started process 1224 to run task
[2025-07-24T15:54:44.870+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '1213', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpkqit_swx']
[2025-07-24T15:54:44.875+0000] {standard_task_runner.py:88} INFO - Job 1213: Subtask Load_songplays_fact_table
[2025-07-24T15:54:44.968+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [running]> on host c53547d84df1
[2025-07-24T15:54:45.063+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:00:00+00:00'
[2025-07-24T15:54:45.855+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 173, in <lambda>
    python_callable=lambda: load_table(SqlQueries.songplay_table_insert, 'songplays'),
  File "/opt/airflow/dags/etl_pipeline.py", line 132, in load_table
    cur.execute(f"INSERT INTO {table} {query}")
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "songplays_pkey"
DETAIL:  Key (playid)=(e30eb65b5ce5534fed9764a7996916ec) already exists.

[2025-07-24T15:54:45.986+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T000000, start_date=20250724T155444, end_date=20250724T155445
[2025-07-24T15:54:46.103+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1213 for task Load_songplays_fact_table (duplicate key value violates unique constraint "songplays_pkey"
DETAIL:  Key (playid)=(e30eb65b5ce5534fed9764a7996916ec) already exists.
; 1224)
[2025-07-24T15:54:46.201+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T15:54:46.396+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T16:34:24.326+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2025-07-24T16:34:24.349+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2025-07-24T16:34:24.350+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T16:34:24.374+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 00:00:00+00:00
[2025-07-24T16:34:24.388+0000] {standard_task_runner.py:60} INFO - Started process 1224 to run task
[2025-07-24T16:34:24.394+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '1619', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp_md9od2h']
[2025-07-24T16:34:24.400+0000] {standard_task_runner.py:88} INFO - Job 1619: Subtask Load_songplays_fact_table
[2025-07-24T16:34:24.549+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [running]> on host c53547d84df1
[2025-07-24T16:34:24.692+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:00:00+00:00'
[2025-07-24T16:34:37.446+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-24T16:34:37.463+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T000000, start_date=20250724T163424, end_date=20250724T163437
[2025-07-24T16:34:37.534+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-24T16:34:37.576+0000] {taskinstance.py:3280} INFO - 4 downstream tasks scheduled from follow-on schedule check
[2025-07-24T17:13:22.405+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2025-07-24T17:13:22.420+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2025-07-24T17:13:22.421+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T17:13:22.442+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 00:00:00+00:00
[2025-07-24T17:13:22.450+0000] {standard_task_runner.py:60} INFO - Started process 1202 to run task
[2025-07-24T17:13:22.455+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '2012', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp1aczcuhv']
[2025-07-24T17:13:22.459+0000] {standard_task_runner.py:88} INFO - Job 2012: Subtask Load_songplays_fact_table
[2025-07-24T17:13:22.572+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T00:00:00+00:00 [running]> on host 5def55d2a1b5
[2025-07-24T17:13:22.656+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T00:00:00+00:00'
[2025-07-24T17:13:33.965+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-24T17:13:33.984+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T000000, start_date=20250724T171322, end_date=20250724T171333
[2025-07-24T17:13:34.028+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-24T17:13:34.060+0000] {taskinstance.py:3280} INFO - 4 downstream tasks scheduled from follow-on schedule check
