[2025-07-22T10:32:38.553+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [queued]>
[2025-07-22T10:32:38.561+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [queued]>
[2025-07-22T10:32:38.562+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-22T10:32:38.657+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 03:00:00+00:00
[2025-07-22T10:32:38.669+0000] {standard_task_runner.py:60} INFO - Started process 228 to run task
[2025-07-22T10:32:38.675+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T03:00:00+00:00', '--job-id', '271', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpwz4wxksu']
[2025-07-22T10:32:38.679+0000] {standard_task_runner.py:88} INFO - Job 271: Subtask Load_songplays_fact_table
[2025-07-22T10:32:38.897+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [running]> on host a2a13a541787
[2025-07-22T10:32:39.221+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T03:00:00+00:00'
[2025-07-22T10:32:39.229+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 168, in <lambda>
    python_callable=lambda: load_table(SqlQueries.songplay_table_insert),
  File "/opt/airflow/dags/etl_pipeline.py", line 127, in load_table
    cur.execute(f"DELETE FROM {query.split()[3]}")
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 1: DELETE FROM events.start_time)
                                     ^

[2025-07-22T10:32:39.244+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T030000, start_date=20250722T103238, end_date=20250722T103239
[2025-07-22T10:32:39.258+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 271 for task Load_songplays_fact_table (syntax error at or near ")"
LINE 1: DELETE FROM events.start_time)
                                     ^
; 228)
[2025-07-22T10:32:39.290+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-22T10:32:39.316+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T15:59:23.487+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [queued]>
[2025-07-24T15:59:23.499+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [queued]>
[2025-07-24T15:59:23.500+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T15:59:23.512+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 03:00:00+00:00
[2025-07-24T15:59:23.519+0000] {standard_task_runner.py:60} INFO - Started process 1388 to run task
[2025-07-24T15:59:23.521+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T03:00:00+00:00', '--job-id', '1245', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpe4g05nh_']
[2025-07-24T15:59:23.524+0000] {standard_task_runner.py:88} INFO - Job 1245: Subtask Load_songplays_fact_table
[2025-07-24T15:59:23.590+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [running]> on host c53547d84df1
[2025-07-24T15:59:23.653+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T03:00:00+00:00'
[2025-07-24T15:59:25.356+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 173, in <lambda>
    python_callable=lambda: load_table(SqlQueries.songplay_table_insert, 'songplays'),
  File "/opt/airflow/dags/etl_pipeline.py", line 132, in load_table
    cur.execute(f"INSERT INTO {table} {query}")
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "songplays_pkey"
DETAIL:  Key (playid)=(e30eb65b5ce5534fed9764a7996916ec) already exists.

[2025-07-24T15:59:25.368+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T030000, start_date=20250724T155923, end_date=20250724T155925
[2025-07-24T15:59:25.429+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1245 for task Load_songplays_fact_table (duplicate key value violates unique constraint "songplays_pkey"
DETAIL:  Key (playid)=(e30eb65b5ce5534fed9764a7996916ec) already exists.
; 1388)
[2025-07-24T15:59:25.462+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T15:59:25.486+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T16:34:29.678+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [queued]>
[2025-07-24T16:34:29.690+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [queued]>
[2025-07-24T16:34:29.691+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T16:34:29.708+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 03:00:00+00:00
[2025-07-24T16:34:29.718+0000] {standard_task_runner.py:60} INFO - Started process 1235 to run task
[2025-07-24T16:34:29.730+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T03:00:00+00:00', '--job-id', '1623', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpx1d8vrr9']
[2025-07-24T16:34:29.739+0000] {standard_task_runner.py:88} INFO - Job 1623: Subtask Load_songplays_fact_table
[2025-07-24T16:34:29.817+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [running]> on host c53547d84df1
[2025-07-24T16:34:29.917+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T03:00:00+00:00'
[2025-07-24T16:34:37.676+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-24T16:34:37.694+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T030000, start_date=20250724T163429, end_date=20250724T163437
[2025-07-24T16:34:37.751+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-24T16:34:37.827+0000] {taskinstance.py:3280} INFO - 4 downstream tasks scheduled from follow-on schedule check
[2025-07-24T17:13:30.991+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [queued]>
[2025-07-24T17:13:31.003+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [queued]>
[2025-07-24T17:13:31.004+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T17:13:31.021+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_songplays_fact_table> on 2023-01-02 03:00:00+00:00
[2025-07-24T17:13:31.039+0000] {standard_task_runner.py:60} INFO - Started process 1215 to run task
[2025-07-24T17:13:31.045+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_songplays_fact_table', 'scheduled__2023-01-02T03:00:00+00:00', '--job-id', '2016', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmprg9cr_h1']
[2025-07-24T17:13:31.054+0000] {standard_task_runner.py:88} INFO - Job 2016: Subtask Load_songplays_fact_table
[2025-07-24T17:13:31.202+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_songplays_fact_table scheduled__2023-01-02T03:00:00+00:00 [running]> on host 5def55d2a1b5
[2025-07-24T17:13:31.333+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T03:00:00+00:00'
[2025-07-24T17:13:34.201+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-24T17:13:34.214+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=tune_stream_dag, task_id=Load_songplays_fact_table, execution_date=20230102T030000, start_date=20250724T171330, end_date=20250724T171334
[2025-07-24T17:13:34.351+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-24T17:13:34.399+0000] {taskinstance.py:3280} INFO - 4 downstream tasks scheduled from follow-on schedule check
