[2025-07-24T15:23:01.543+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_time_dim_table scheduled__2023-01-05T08:00:00+00:00 [queued]>
[2025-07-24T15:23:01.553+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_time_dim_table scheduled__2023-01-05T08:00:00+00:00 [queued]>
[2025-07-24T15:23:01.554+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T15:23:01.567+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_time_dim_table> on 2023-01-05 08:00:00+00:00
[2025-07-24T15:23:01.574+0000] {standard_task_runner.py:60} INFO - Started process 879 to run task
[2025-07-24T15:23:01.578+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_time_dim_table', 'scheduled__2023-01-05T08:00:00+00:00', '--job-id', '891', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmp34462u_4']
[2025-07-24T15:23:01.582+0000] {standard_task_runner.py:88} INFO - Job 891: Subtask Load_time_dim_table
[2025-07-24T15:23:01.656+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_time_dim_table scheduled__2023-01-05T08:00:00+00:00 [running]> on host c53547d84df1
[2025-07-24T15:23:01.783+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-05T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-05T08:00:00+00:00'
[2025-07-24T15:23:01.793+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_pipeline.py", line 197, in <lambda>
    python_callable=lambda: load_table(SqlQueries.time_table_insert, 'time'),
  File "/opt/airflow/dags/etl_pipeline.py", line 132, in load_table
    cur.execute(f"INSERT INTO {table} {query}")
psycopg2.errors.InvalidParameterValue: timestamp units "dayofweek" not recognized

[2025-07-24T15:23:01.806+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tune_stream_dag, task_id=Load_time_dim_table, execution_date=20230105T080000, start_date=20250724T152301, end_date=20250724T152301
[2025-07-24T15:23:01.819+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 891 for task Load_time_dim_table (timestamp units "dayofweek" not recognized
; 879)
[2025-07-24T15:23:01.832+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T15:23:01.855+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T17:33:40.029+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tune_stream_dag.Load_time_dim_table scheduled__2023-01-05T08:00:00+00:00 [queued]>
[2025-07-24T17:33:40.069+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tune_stream_dag.Load_time_dim_table scheduled__2023-01-05T08:00:00+00:00 [queued]>
[2025-07-24T17:33:40.072+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T17:33:40.221+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Load_time_dim_table> on 2023-01-05 08:00:00+00:00
[2025-07-24T17:33:40.275+0000] {standard_task_runner.py:60} INFO - Started process 3536 to run task
[2025-07-24T17:33:40.288+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tune_stream_dag', 'Load_time_dim_table', 'scheduled__2023-01-05T08:00:00+00:00', '--job-id', '2703', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpwf0iok3g']
[2025-07-24T17:33:40.321+0000] {standard_task_runner.py:88} INFO - Job 2703: Subtask Load_time_dim_table
[2025-07-24T17:33:40.800+0000] {task_command.py:423} INFO - Running <TaskInstance: tune_stream_dag.Load_time_dim_table scheduled__2023-01-05T08:00:00+00:00 [running]> on host 5def55d2a1b5
[2025-07-24T17:33:41.406+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='genz-legend' AIRFLOW_CTX_DAG_ID='tune_stream_dag' AIRFLOW_CTX_TASK_ID='Load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2023-01-05T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-05T08:00:00+00:00'
[2025-07-24T17:33:41.815+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-07-24T17:33:41.885+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=tune_stream_dag, task_id=Load_time_dim_table, execution_date=20230105T080000, start_date=20250724T173340, end_date=20250724T173341
[2025-07-24T17:33:42.331+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-07-24T17:33:42.573+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
