[2025-07-21T20:19:40.325+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branching_primes_dag.print_number_bash manual__2025-07-21T20:19:37.295647+00:00 [queued]>
[2025-07-21T20:19:40.337+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branching_primes_dag.print_number_bash manual__2025-07-21T20:19:37.295647+00:00 [queued]>
[2025-07-21T20:19:40.337+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-21T20:19:40.350+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): print_number_bash> on 2025-07-21 20:19:37.295647+00:00
[2025-07-21T20:19:40.355+0000] {standard_task_runner.py:60} INFO - Started process 87 to run task
[2025-07-21T20:19:40.360+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'branching_primes_dag', 'print_number_bash', 'manual__2025-07-21T20:19:37.295647+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/number_dag.py', '--cfg-path', '/tmp/tmp5aw0k47d']
[2025-07-21T20:19:40.363+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask print_number_bash
[2025-07-21T20:19:40.439+0000] {task_command.py:423} INFO - Running <TaskInstance: branching_primes_dag.print_number_bash manual__2025-07-21T20:19:37.295647+00:00 [running]> on host ffddf4fc22f7
[2025-07-21T20:19:40.481+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'print_number_bash', field 'bash_command'. Template: 'echo "The input number is: {{ dag_run.conf["number"] }}"'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'number'
[2025-07-21T20:19:40.484+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'number'
[2025-07-21T20:19:40.494+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=branching_primes_dag, task_id=print_number_bash, execution_date=20250721T201937, start_date=20250721T201940, end_date=20250721T201940
[2025-07-21T20:19:40.506+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 52 for task print_number_bash ('dict object' has no attribute 'number'; 87)
[2025-07-21T20:19:40.532+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-21T20:19:40.549+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
